### ISSUE TITLE
Waitlist Sign-Up Form - Modal

### ISSUE THREAD

**Issue by cynthialmy** [otoaneba/akaboo#1]
Sign-Up Form
- **Form Fields**: Minimal fields such as: 

    - Name, 
    - Email,
    - optional Zip Code, 
    - optional Child’s Age Range, 
    - optional interest in buy or sell or both, 
    - optional categories to buy {stroller, car seat, carrier, crib, etc.}.

- **Submit Button**: "Secure My Spot!"
- **Privacy Statement**: 

> At Akaboo, your privacy is paramount. We collect your name, email, and other optional details exclusively to enhance your experience and keep you informed about our services. Your data is kept confidential, never sold, and is protected with robust security measures. You may update or delete your information anytime by contacting us.
> 
> By submitting this form, you agree to our data practices as described here and in our full [Privacy Policy](https://cynthiali-abe.notion.site/Privacy-Statement-2fd620cdb08343adbd11c9e45bb8e0ff?pvs=4). For any concerns, reach out to spiceitglobal@gmail.com.

Privacy Policy Link: https://cynthiali-abe.notion.site/Privacy-Statement-2fd620cdb08343adbd11c9e45bb8e0ff?pvs=4

**Comment by otoaneba** [comment]
Roger. I've started on the assignment.
